# Loads default set of integrations. Remove default_config
# and this component if you only want to test myq_garage.
default_config:

logger:
  default: info
  logs:
    custom_components.myq_garage: debug
